### ISSUE TITLE
Warning: unable to extract comment count

### ISSUE THREAD

**Issue by snsa00** [Maslosoft/Playlist#8]
Downloading videos from Dailymotion always end up in error

 when the download begins i get this error 

WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

and then after downloading  part of the file  Download returns the error 
ERROR: content too short (expected 650496191 bytes and served 561284604)

i restart the download  every time it stops in error and eventually i was  able to download the complete file.

here is the complete verbose listing of one of the files  downloaded.

// Begin Listing //

﻿youtube-dl -i --verbose http://www.dailymotion.com/video/x55gc6w_bigg-boss-10-16th-december-2016-full-episode-hd_tv
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-i', u'--verbose', u'http://www.dailymotion.com/video/x55gc6w_bigg-boss-10-16th-december-2016-full-episode-hd_tv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.15
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 2.8.8, ffprobe 2.8.8
[debug] Proxy map: {}
[dailymotion] x55gc6w: Downloading webpage
WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[dailymotion] x55gc6w: Downloading m3u8 information
[dailymotion] x55gc6w: Downloading m3u8 information
[dailymotion] x55gc6w: Downloading m3u8 information
[dailymotion] x55gc6w: Downloading m3u8 information
[dailymotion] x55gc6w: Downloading m3u8 information
[dailymotion] x55gc6w: Downloading m3u8 information
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-1280x720/video/x55gc6w.mp4?auth=1482102264-2562-pdwn5zug-584abbd3c8033fe4837b528bd614ee29'
[download] Resuming download at byte 353350709
[download] Destination: Bigg Boss 10 16th December 2016 Full Episode HD-x55gc6w.mp4
[download]  63.2% of 609.78MiB at 296.34KiB/s ETA 12:55ERROR: content too short (expected 639405294 bytes and served 403979576)
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 238, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError

// End Listing //

**Comment by pmaselkowski** [comment]
Seems that this issue is posted in wrong project, please post it here: https://github.com/rg3/youtube-dl/issues
